sudo: false
language: python
cache: pip
python:
  - "3.3"
env:
  TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=docs
  allow_failures:
    - python: "nightly"

install:
  - [ $TRAVIS_PYTHON_VERSION == "3.3" ] && pip install wheel<=0.30.0
  - pip install -U six && pip install -U tox
  - ./ci_tools/retry.sh python updatezinfo.py

script:
  - tox

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi

