language: python
cache: pip
python:
  - "3.7"
env:
  TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=build

install:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then
      pip install -U "pip==10.0.1"
      PIP_ARGS="-c requirements/3.3/constraints.txt"
    fi
  - pip install -U "tox<3.8.0" $PIP_ARGS
  - if [[ $TOXENV == "py" ]]; then ./ci_tools/retry.sh python updatezinfo.py; fi

script:
  - tox
  - echo $TOXENV
  - if [[ $TOXENV == "build" ]]; then echo "Hi" && [ ! -e "dist/*.whl" ] && [ ! -e "dist/*.tar.gz" ]; fi
  - ls dist

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
