language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4"
  - "pypy3"

matrix:
  allow_failures:
    - python: "nightly"

before_install:
  # Install test dependencies
  - pip install -r requirements-dev.txt
  - pip install codecov

install:
  - COVERAGE_FILE=.coverage.rebuild coverage run --source=dateutil.zoneinfo updatezinfo.py

  - if pip freeze | grep dateutil; then pip uninstall -y python-dateutil; fi
  
  # Install the libraries
  - pip install .

before_script:
  # Run the script from something other than the repo root
  - mkdir -p build_test/dateutil
  - cp -pr dateutil/test build_test/dateutil/test
  - cp .coverage.rebuild build_test/.coverage.rebuild
  - cd build_test

script:
  - COVERAGE_FILE=.coverage.main coverage run --source=dateutil,test -m pytest -v

after_success:
  - coverage combine
  - coverage report -m
  - codecov

sudo: false
