name: EOL and dev tests

on:
  - pull_request
  - schedule:
    # Run at 00:30 daily
    - cron: 30 0 * * *

jobs:
  tests:
      # These are tests for EOL and dev versions of Python
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.3", "3.4", "3.5", "3.9-dev", "3.10-dev"]
          os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      TOXENV: py
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.python-version }} - ${{ matrix.os }}
        if: "!startsWith(matrix.python-version, '3.3')"
        uses: deadsnakes/action@v1.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: ${{ matrix.python-version }} - ${{ matrix.os }}
        if: "startsWith(matrix.python-version, '3.3')"
        uses: "pganssle/action@5dd839709ba560788c65d0fb1e11cfd7cd2b3ce8"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          if [[ ${{ matrix.python-version }} == "3.3" ]]; then
            python -m pip install -U "pip==10.0.1"
            export PIP_CONSTRAINT="requirements/3.3/constraints.txt"
          fi
          python -m pip install tox
      - name: Run tests
        run: python -m tox
